# Generated by Django 5.2.4 on 2025-07-11 19:19

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_ltrs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_ltr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('official_id', models.CharField(max_length=100, verbose_name=users.models.User)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='users.user')),
            ],
        ),
    ]
