# Generated by Django 5.2.3 on 2025-06-25 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativeOfficials', '0001_initial'),
        ('milkRecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='official_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='cooperativeOfficials.cooperativeofficial'),
        ),
    ]
