# Generated by Django 5.2.3 on 2025-07-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price_per_ltr',
        ),
    ]
