# Generated by Django 5.2.4 on 2025-07-10 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('member_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='farmer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Payments.farmer'),
            preserve_default=False,
        ),
    ]
