# Generated by Django 5.2.4 on 2025-07-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_farmer_payment_farmer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='member_id',
        ),
    ]
