# Generated by Django 5.2.4 on 2025-07-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_remove_farmer_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='farmer_id',
        ),
    ]
