# Generated by Django 5.2.4 on 2025-07-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_remove_payment_farmer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
