# Generated by Django 5.2.4 on 2025-07-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkRecords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkrecord',
            old_name='farmer_id',
            new_name='member_id',
        ),
        migrations.RemoveField(
            model_name='milkrecord',
            name='official_id',
        ),
    ]
