# Generated by Django 5.2.3 on 2025-07-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkRecords', '0002_rename_farmer_id_milkrecord_member_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkrecord',
            name='price_per_ltr',
        ),
        migrations.RemoveField(
            model_name='milkrecord',
            name='quantity_ltrs',
        ),
    ]
