# Generated by Django 5.2.3 on 2025-07-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkRecords', '0003_remove_milkrecord_price_per_ltr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
